name: DyeMaster
version: '${project.version}'
main: me.dyemaster.DyeMaster
api-version: '1.20'
author: 7azeemm
commands:
  dyes:
    description: Opens dye gui
    aliases: dyemaster
    permission: dyemaster.gui
permissions:
  dyemaster.gui:
    description: allows to run /dyes command to open dyes menu
    default: op
  dyemaster.dyearmor:
    description: allows player to dye leather armor with custom dye
    default: op
  dyemaster.craftdye:
    description: allows player to craft custom dye
    default: op
