name: DyeMaster
version: '${project.version}'
main: me.dyemaster.DyeMaster
api-version: '1.20'
author: 7azeemm
commands:
  dyes:
    description: Opens dye gui
    aliases: dyemaster
    permission: dyemaster.gui
permissions:
  dyemaster.gui:
    description: allows the user to run /dyes command to open dyes menu.
    default: op
  dyemaster.dyearmor:
    description: allows the user to apply custom dye to armor.
    default: op
  dyemaster.craftdye:
    description: allows the user to craft custom dye.
    default: op
